### PR TITLE
User login and register updated

### PR DESCRIPTION
**Pull request by Muskan02**
I have improved the login and register form UI.

### CODE REVIEW

**Comment by manav014** [comment]
Please remove the conflicting files and the unnecessary files. You may use the following command for the same.
`git add modified_filename` in spite of ` git add .`

**Comment by manav014** [comment]
As the repository is changed please use git pull before using git push

**Comment by Muskan02** [comment]
> As the repository is changed please use git pull before using git push

ok. Please close this pull request. I have made another pull request with no merge conflicts.

**Comment by manav014** [comment]
Closed on your request

**Comment by manav014** [comment]
Thank you for this PR

**Pull request closed without merging**
